Repository pgopr/pgopr, pull requests merged in 2025-05, with the labels that each got.

#8 [#7] Update dependencies
  Cargo.toml
Labels: enhancement

#18 [#10] k8s 1.32.x
  Cargo.toml
Labels: enhancement

#19 [#13] Shell script for rustfmt
  Cargo.toml
  doc/DEVELOPERS.md
  rustfmt.sh
  src/crd.rs
  src/finalizer.rs
  src/main.rs
  src/persistent.rs
  src/primary.rs
  src/services.rs
Labels: feature

#21 [#12] Panick: Missing k8s environment
  src/k8s.rs
Labels: bug

#11 [#9] Initial tutorials
  doc/tutorial/01_install_operator.md
  doc/tutorial/02_provision.md
  doc/tutorial/03_database_access.md
  doc/tutorial/04_retire.md
  doc/tutorial/05_uninstall.md
  doc/tutorial/06_completion.md
  doc/tutorial/07_generate.md
Labels: documentation

#24 [#15] Use PostgreSQL 17
  README.md
  doc/DEVELOPERS.md
  doc/tutorial/03_database_access.md
  src/primary.rs
Labels: enhancement
